version: 2
jobs:
  check_style:
    docker:
      - image: python:3.8.2-buster
    steps:
      - checkout
      - run:
          name: "Install package"
          command: |
            pip install black
      - run:
          name: "Check code style"
          command: |
            black --check smilechat
  test-small:
    docker:
      - image: python:3.8.2-buster
    steps:
      - checkout
      - run:
          name: "Install package"
          command: |
            pip install .
            pip install pytest==5.4.3
      - run:
          name: "Run small size tests"
          command: |
            pytest -v tests/small
      - run:
          name: "Run CLI tests"
          command: |
            mkdir work
            cd work
            python -m smilechat.main init
            echo Hello | python -m smilechat.main run --config_file=config.yml
            cd ..
