# ===== [Service] =====

# CLI Service
service:
  name: pybot.service.CliService
  config:
    user_name: you

# Twitter service
#service:
#  name: pybot.service.TwitterStreamSampleService
#  config:
#    consumer_key: ""
#    consumer_secret: ""
#    access_token_key: ""
#    access_token_secret: ""
#    lang: ja


# ===== [Post Service] =====
# If you want to use different service to post your message,
# define post service.

#post_service:
#  name: pybot.service.CliService
#  config:
#    user_name: you


# ===== [App] =====
# Define your app here

app:
  name: app.MyApp
