site_name: SmileChat
theme:
  name: material
  palette:
    primary: white
    accent: white
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Development: development.md
  - Change Log: CHANGELOG.md
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.magiclink
  - admonition
  - codehilite:
      linenums: true
      use_pygments: true

# Add source repository
repo_name: noriyukipy/msgflow
repo_url: https://github.com/noriyukipy/msgflow