name: unittest
on: [push]
jobs:
  test-small:
    runs-on: ubuntu-18.04
    container:
      image: python:3.9.1-slim-buster
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install .[test,cron]
      - name: Run small size tests
        run: |
          pytest -v tests/small
      - name: Run CLI tests
        run: |
          mkdir work
          cd work
          python -m msgflow.main init
          echo Hello | python -m msgflow.main run --config_file=config.yml
          cd ..
      - name: Check code style
        run: black --check msgflow tests